const express=require('express');
const router=express.Router();
const db= require('../config/mongoose');
const tasksdb=require('../models/tasks');
const home_controller=require('../controllers/home_controller');
const delete_task_controller=require('../controllers/delete_task_controller');
const create_task_controller=require('../controllers/create_task_controller');
const toggle_task_controller=require('../controllers/toggle_task_controller');
//console.log(typeof delete_task_controller,typeof home_controller);
router.get('/',home_controller);
router.post('/create-task',create_task_controller);
router.post('/delete-task',delete_task_controller);
//router.get('/toggle-task',toggle_task_controller);
module.exports=router;